version: "3.9"

services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
  #Node API services
  api:
    build: .
    volumes:
      - .:/app
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo_db
  nginx:
    image: nginx:latest
    volumes:
      - .conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 5000:5000
volumes:
  mongodb:
